Repository scs/substrate-api-client, pull requests merged in 2022-12, with the labels that each got.

#349 Update README.md
  README.md
Labels: E1-breaksnothing, E0-silent

#350 Add encointer to used projects in README
  README.md
Labels: E1-breaksnothing, E0-silent

#352 Add Litentry to using projects
  README.md
Labels: E1-breaksnothing, E0-silent

#359 updated and added usage of ajuna network
  README.md
Labels: E1-breaksnothing, E0-silent

#311 Add license check to CI
  .github/workflows/ci.yml
  Cargo.lock
  about.hbs
  about.toml
Labels: F3-test, E1-breaksnothing

#355 Support `tungstenite-rs` rpc client
  Cargo.lock
  Cargo.toml
  examples/benchmark_bulk_xt.rs
  examples/compose_extrinsic_offline.rs
  examples/custom_nonce.rs
  examples/event_callback.rs
  examples/event_error_details.rs
  examples/generic_event_callback.rs
  examples/generic_extrinsic.rs
  examples/get_account_identity.rs
  examples/get_blocks.rs
  examples/get_existential_deposit.rs
  examples/get_storage.rs
  examples/print_metadata.rs
  examples/sudo.rs
  examples/transfer_using_seed.rs
  src/api/api_client.rs
  src/api/error.rs
  src/api/mod.rs
  src/api/subscription.rs
  src/rpc/error.rs
  src/rpc/mod.rs
  src/rpc/tungstenite_client/client.rs
  src/rpc/tungstenite_client/mod.rs
  src/rpc/ws_client/client.rs
  src/rpc/ws_client/mod.rs
Labels: F7-enhancement, E1-breaksnothing

#354 Enhance rpc interface and simplify ws client
  .taplo.toml
  Cargo.lock
  Cargo.toml
  compose-macros/src/lib.rs
  compose-macros/src/rpc.rs
  examples/batch_payout.rs
  examples/benchmark_bulk_xt.rs
  examples/compose_extrinsic_offline.rs
  examples/contract_instantiate_with_code.rs
  examples/custom_nonce.rs
  examples/event_callback.rs
  examples/event_error_details.rs
  examples/generic_event_callback.rs
  examples/generic_extrinsic.rs
  examples/get_account_identity.rs
  examples/get_blocks.rs
  examples/get_existential_deposit.rs
  examples/get_storage.rs
  examples/print_metadata.rs
  examples/staking_payout.rs
  examples/sudo.rs
  examples/transfer_using_seed.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/pallet_traits/frame_system_config.rs
  primitives/src/pallet_traits/pallet_balances_config.rs
  primitives/src/rpc_params.rs
  src/api/api_client.rs
  src/api/error.rs
  src/api/mod.rs
  src/api/subscription.rs
  src/extrinsic/balances.rs
  src/extrinsic/contracts.rs
  src/extrinsic/staking.rs
  src/extrinsic/utility.rs
  src/rpc/error.rs
  src/rpc/json_req.rs
  src/rpc/mod.rs
  src/rpc/tungstenite_client/client.rs
  src/rpc/tungstenite_client/mod.rs
  src/rpc/tungstenite_client/subscription.rs
  src/rpc/ws_client/client.rs
  src/rpc/ws_client/mod.rs
  src/rpc/ws_client/subscription.rs
Labels: F7-enhancement, E2-breaksapi

#365 Added Polkadex in substrate-api-client readme
  README.md
Labels: E1-breaksnothing, E0-silent

#363 Add api traits
  Cargo.toml
  compose-macros/src/lib.rs
  examples/batch_payout.rs
  examples/benchmark_bulk_xt.rs
  examples/compose_extrinsic_offline.rs
  examples/contract_instantiate_with_code.rs
  examples/custom_nonce.rs
  examples/event_callback.rs
  examples/event_error_details.rs
  examples/generic_event_callback.rs
  examples/generic_extrinsic.rs
  examples/get_account_identity.rs
  examples/get_blocks.rs
  examples/get_existential_deposit.rs
  examples/get_storage.rs
  examples/staking_payout.rs
  examples/sudo.rs
  examples/transfer_using_seed.rs
  examples/transfer_with_tungstenite_client.rs
  examples/transfer_with_ws_client.rs
  node-api/src/metadata.rs
  node-api/src/storage.rs
  primitives/src/pallet_traits/frame_system_config.rs
  src/api/api_client.rs
  src/api/error.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/chain.rs
  src/api/rpc_api/frame_system.rs
  src/api/rpc_api/mod.rs
  src/api/rpc_api/pallet_balances.rs
  src/api/rpc_api/pallet_transaction_payment.rs
  src/api/rpc_api/state.rs
  src/api/rpc_api/subscribe_events.rs
  src/api/subscription.rs
  src/extrinsic/balances.rs
  src/extrinsic/contracts.rs
  src/extrinsic/staking.rs
  src/extrinsic/utility.rs
Labels: F7-enhancement, E1-breaksnothing

#372 Clean up tomls
  Cargo.lock
  Cargo.toml
  node-api/Cargo.toml
  primitives/Cargo.toml
Labels: E1-breaksnothing

#374 Fix bugs and remove unused Clone / Debug enforcements
  primitives/src/types.rs
  src/api/mod.rs
  src/api/rpc_api/pallet_transaction_payment.rs
  src/api/rpc_api/state.rs
Labels: F2-bug, E1-breaksnothing

#371 Move exampels to separate crate
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  README.md
  examples/Cargo.toml
  examples/examples/batch_payout.rs
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/event_callback.rs
  examples/examples/event_error_details.rs
  examples/examples/generic_event_callback.rs
  examples/examples/generic_extrinsic.rs
  examples/examples/get_account_identity.rs
  examples/examples/get_blocks.rs
  examples/examples/get_existential_deposit.rs
  examples/examples/get_storage.rs
  examples/examples/print_metadata.rs
  examples/examples/staking_payout.rs
  examples/examples/sudo.rs
  examples/examples/transfer_using_seed.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
Labels: E1-breaksnothing

#368 Add new test crate
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  examples/examples/get_existential_deposit.rs
  testing/Cargo.toml
  testing/examples/author_tests.rs
  testing/examples/chain_tests.rs
  testing/examples/frame_system_tests.rs
  testing/examples/pallet_balances_tests.rs
  testing/examples/pallet_transaction_payment_tests.rs
  testing/examples/state_tests.rs
Labels: F3-test, E1-breaksnothing

#384 Make api/rpc interfaces no_std compatible
  Cargo.lock
  Cargo.toml
  compose-macros/src/lib.rs
  primitives/src/rpc_params.rs
  src/lib.rs
  src/rpc/error.rs
  src/rpc/mod.rs
  src/utils.rs
Labels: E1-breaksnothing

#387 run CI also on polkadot branches
  .github/workflows/ci.yml
Labels: F3-test, E0-silent

#389 Fix ci.yml
  .github/workflows/ci.yml
Labels: E0-silent

#390 Udpate to newest substrate master commit
  Cargo.lock
  primitives/src/pallet_traits/frame_system_config.rs
Labels: E1-breaksnothing

#392 Fix readme and remove outdated CHANGELOG.md
  CHANGELOG.md
  README.md
Labels: E0-silent

#386 SubmitAndWatch: Return `ExtrinsicReport` instead of block hash
  examples/examples/batch_payout.rs
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/event_error_details.rs
  examples/examples/generic_event_callback.rs
  examples/examples/generic_extrinsic.rs
  examples/examples/get_account_identity.rs
  examples/examples/staking_payout.rs
  examples/examples/sudo.rs
  examples/examples/transfer_using_seed.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
  node-api/src/events.rs
  primitives/src/extrinsics.rs
  src/api/error.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/chain.rs
  src/api/rpc_api/pallet_transaction_payment.rs
  src/api/rpc_api/subscribe_events.rs
  src/utils.rs
  testing/examples/author_tests.rs
  testing/examples/pallet_transaction_payment_tests.rs
Labels: F7-enhancement, E2-breaksapi

#396 Fix in `XtStatus::InBlock` as u8
  src/api/mod.rs
Labels: F2-bug, E1-breaksnothing

#394 Add helper methode api.compose_extrsinic_offline
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/custom_nonce.rs
  examples/examples/generic_extrinsic.rs
  examples/examples/sudo.rs
  src/extrinsic/mod.rs
  src/extrinsic/offline_extrinsic.rs
Labels: F7-enhancement, E1-breaksnothing

#377 Make Api `no_std` compatible
  Cargo.lock
  Cargo.toml
  node-api/Cargo.toml
  node-api/src/lib.rs
  node-api/src/metadata.rs
  node-api/src/storage.rs
  primitives/Cargo.toml
  primitives/src/extrinsic_params.rs
  primitives/src/extrinsics.rs
  primitives/src/lib.rs
  primitives/src/pallet_traits/frame_system_config.rs
  primitives/src/pallet_traits/pallet_assets_config.rs
  primitives/src/pallet_traits/pallet_balances_config.rs
  primitives/src/pallet_traits/pallet_staking_config.rs
  primitives/src/rpc_numbers.rs
  primitives/src/rpc_params.rs
  primitives/src/serde_impls.rs
  primitives/src/types.rs
  src/api/api_client.rs
  src/api/error.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/chain.rs
  src/api/rpc_api/frame_system.rs
  src/api/rpc_api/pallet_transaction_payment.rs
  src/api/rpc_api/state.rs
  src/api/rpc_api/subscribe_events.rs
  src/extrinsic/balances.rs
  src/extrinsic/common.rs
  src/extrinsic/contracts.rs
  src/extrinsic/utility.rs
  src/lib.rs
  src/utils.rs
Labels: E1-breaksnothing

#399 Add TransactionStatus and Api unit tests
  Cargo.toml
  ksm_metadata_v14.bin
  src/api/api_client.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
  src/rpc/mocks.rs
  src/rpc/mod.rs
  src/utils.rs
  testing/examples/author_tests.rs
Labels: F3-test, E1-breaksnothing
