Repository scs/substrate-api-client, pull requests merged in 2023-01, with the labels that each got.

#401 Clean up examples
  .github/workflows/ci.yml
  README.md
  examples/examples/batch_payout.rs
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/event_callback.rs
  examples/examples/event_error_details.rs
  examples/examples/generic_event_callback.rs
  examples/examples/generic_extrinsic.rs
  examples/examples/get_account_identity.rs
  examples/examples/get_blocks.rs
  examples/examples/get_storage.rs
  examples/examples/print_metadata.rs
  examples/examples/staking_payout.rs
  examples/examples/sudo.rs
  examples/examples/transfer_using_seed.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
Labels: Z3-example, E1-breaksnothing

#402 Add some system helper functions
  primitives/src/types.rs
  src/api/rpc_api/frame_system.rs
  testing/examples/frame_system_tests.rs
Labels: F7-enhancement, E1-breaksnothing

#403 Add `get_storage_keys_paged`
  examples/examples/get_storage.rs
  src/api/rpc_api/state.rs
  testing/examples/state_tests.rs
Labels: F7-enhancement, E1-breaksnothing

#408 Update to the newest substrate commit + cargo update
  Cargo.lock
  primitives/src/pallet_traits/pallet_staking_config.rs
Labels: E1-breaksnothing

#409 Update .toml version
  Cargo.lock
  Cargo.toml
  compose-macros/Cargo.toml
  node-api/Cargo.toml
  primitives/Cargo.toml
Labels: E1-breaksnothing

#417 Fix documentation for running an example.
  README.md
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/custom_nonce.rs
  examples/examples/sudo.rs
Labels: E0-silent

#419 Remove thiserror
  Cargo.lock
  Cargo.toml
  src/api/api_client.rs
  src/api/error.rs
  src/rpc/error.rs
  src/rpc/tungstenite_client/client.rs
  src/rpc/ws_client/client.rs
  src/rpc/ws_client/mod.rs
Labels: F6-optimization, E2-breaksapi

#421 Enforce `UncheckedExtrinsicV4` for `submit_extrinsic` and add `_opaque_extrinsic`
  examples/examples/batch_payout.rs
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/event_error_details.rs
  examples/examples/get_account_identity.rs
  examples/examples/sudo.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
  src/api/rpc_api/author.rs
  testing/examples/author_tests.rs
Labels: F7-enhancement, E2-breaksapi

#425 Update toolchain to 2023-01-05
  client-keystore/src/lib.rs
  node-api/src/print_metadata.rs
  rust-toolchain.toml
  src/api/rpc_api/author.rs
  src/rpc/error.rs
Labels: E1-breaksnothing

#424 Clean up Api Error and indicate future status clearly
  examples/examples/custom_nonce.rs
  node-api/src/lib.rs
  src/api/error.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
Labels: F7-enhancement, E2-breaksapi

#423 Enforce `Bytes` and remove obsolete hex-utils
  src/api/api_client.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/chain.rs
  src/api/rpc_api/frame_system.rs
  src/api/rpc_api/pallet_transaction_payment.rs
  src/api/rpc_api/state.rs
  src/lib.rs
  src/utils.rs
  testing/examples/pallet_transaction_payment_tests.rs
Labels: F7-enhancement, E2-breaksapi

#428 add `submit_and_watch_until_success` to examples
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/event_error_details.rs
  src/api/rpc_api/author.rs
Labels: Z3-example, E1-breaksnothing

#418 Make UncheckedExtrinsicV4 generic
  compose-macros/src/lib.rs
  examples/examples/batch_payout.rs
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/event_callback.rs
  examples/examples/event_error_details.rs
  examples/examples/get_account_identity.rs
  examples/examples/get_storage.rs
  examples/examples/sudo.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
  primitives/src/extrinsics.rs
  primitives/src/lib.rs
  primitives/src/signer.rs
  src/api/api_client.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/frame_system.rs
  src/extrinsic/balances.rs
  src/extrinsic/common.rs
  src/extrinsic/contracts.rs
  src/extrinsic/offline_extrinsic.rs
  src/extrinsic/staking.rs
  src/extrinsic/utility.rs
  testing/examples/author_tests.rs
  testing/examples/frame_system_tests.rs
  testing/examples/pallet_transaction_payment_tests.rs
Labels: F7-enhancement, E2-breaksapi

#433 Add staking example to CI
  .github/workflows/ci.yml
  README.md
  examples/examples/batch_payout.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/event_error_details.rs
  examples/examples/staking_batch_payout.rs
Labels: Z3-example, E1-breaksnothing

#439 Add `no_std` rpc client to readme
  README.md
Labels: F4-documentation, E0-silent

#434 Add traits and remove excessive type definition in extrinsic helpers
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/event_error_details.rs
  examples/examples/staking_batch_payout.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
  src/extrinsic/balances.rs
  src/extrinsic/common.rs
  src/extrinsic/contracts.rs
  src/extrinsic/mod.rs
  src/extrinsic/staking.rs
  src/extrinsic/utility.rs
  testing/examples/author_tests.rs
  testing/examples/events_tests.rs
  testing/examples/pallet_transaction_payment_tests.rs
Labels: F7-enhancement, E2-breaksapi

#437 Remove `wait_for_event` and simplify event access in `subscribe_events`
  examples/examples/event_callback.rs
  node-api/src/lib.rs
  src/api/rpc_api/events.rs
  src/api/rpc_api/frame_system.rs
  testing/examples/events_tests.rs
  testing/examples/frame_system_tests.rs
Labels: F7-enhancement, E2-breaksapi
