Repository scs/substrate-api-client, pull requests merged in 2023-08, with the labels that each got.

#636 Add unit tests for hash matching for unchecked extrinsic
  Cargo.lock
  primitives/Cargo.toml
  primitives/src/extrinsics/extrinsic_params.rs
  primitives/src/extrinsics/mod.rs
  primitives/src/extrinsics/test-runtime.compact.wasm
Labels: F3-test, E1-breaksnothing

#635 Runtime update detector
  .github/workflows/ci.yml
  Cargo.lock
  examples/Cargo.toml
  examples/examples/kitchensink_runtime.compact.compressed.wasm
  examples/examples/print_metadata.rs
  examples/examples/runtime_update_async.rs
  examples/examples/runtime_update_sync.rs
  node-api/src/events/event_details.rs
  src/api/api_client.rs
  src/api/rpc_api/mod.rs
  src/api/rpc_api/runtime_update.rs
Labels: E1-breaksnothing

#639 Prepare for tag v0.14.0
  Cargo.lock
  Cargo.toml
  compose-macros/Cargo.toml
  examples/Cargo.toml
  node-api/Cargo.toml
  primitives/Cargo.toml
  testing/Cargo.toml
Labels: E1-breaksnothing

#642 Increase timeout value
  examples/examples/runtime_update_async.rs
Labels: E0-silent
