Repository scs/substrate-api-client, pull requests merged in 2023-07, with the labels that each got.

#601 Take Bytes parameters as borrow
  src/api/rpc_api/author.rs
  src/api/rpc_api/pallet_transaction_payment.rs
  testing/examples/pallet_transaction_payment_tests.rs
Labels: E2-breaksapi

#602 fetch more storage keys than the maximum limit set by substrate
  src/api/rpc_api/state.rs
  testing/examples/state_tests.rs
Labels: E2-breaksapi

#604 Rename runtime configs to something more generic
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/event_callback.rs
  examples/examples/event_error_details.rs
  examples/examples/get_account_identity.rs
  examples/examples/get_blocks_async.rs
  examples/examples/get_storage.rs
  examples/examples/print_metadata.rs
  examples/examples/staking_batch_payout.rs
  examples/examples/sudo.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
  primitives/src/config/asset_runtime_config.rs
  primitives/src/config/default_runtime_config.rs
  primitives/src/config/mod.rs
  primitives/src/extrinsics/mod.rs
  primitives/src/extrinsics/signer.rs
  src/api/api_client.rs
  src/api/rpc_api/events.rs
  testing/examples/author_tests.rs
  testing/examples/chain_tests.rs
  testing/examples/dispatch_errors_tests.rs
  testing/examples/events_tests.rs
  testing/examples/frame_system_tests.rs
  testing/examples/pallet_balances_tests.rs
  testing/examples/pallet_transaction_payment_tests.rs
  testing/examples/state_tests.rs
Labels: E2-breaksapi

#606 Rework submit and watch extrinsics
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/event_error_details.rs
  examples/examples/get_account_identity.rs
  examples/examples/staking_batch_payout.rs
  examples/examples/sudo.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
  testing/examples/author_tests.rs
  testing/examples/dispatch_errors_tests.rs
  testing/examples/events_tests.rs
Labels: E2-breaksapi

#610 Update README info on project funding
  README.md
Labels: E1-breaksnothing, F4-documentation

#611 Fix comments of default Configs
  primitives/src/config/asset_runtime_config.rs
  primitives/src/config/default_runtime_config.rs
Labels: E1-breaksnothing

#619 Fix some typos
  compose-macros/Cargo.toml
  docs/overview_code_structure.svg
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/sudo.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/events.rs
  src/lib.rs
  testing/examples/author_tests.rs
  testing/examples/events_tests.rs
Labels: E0-silent

#618 Update scale-enode and decode to crates.io
  Cargo.lock
  node-api/Cargo.toml
Labels: E1-breaksnothing, dependencies

#615 Add EventReport and failed xt check to examples
  .github/workflows/ci.yml
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/check_extrinsic_events.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/event_error_details.rs
  examples/examples/get_account_identity.rs
  examples/examples/get_blocks_async.rs
  examples/examples/get_storage.rs
  examples/examples/print_metadata.rs
  examples/examples/staking_batch_payout.rs
  examples/examples/subscribe_events.rs
  examples/examples/sudo.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
  src/api/rpc_api/author.rs
  testing/examples/author_tests.rs
Labels: Z3-example, E1-breaksnothing

#629 Fix reported extrinsic hash
  examples/examples/check_extrinsic_events.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/events.rs
  testing/examples/author_tests.rs
Labels: F2-bug, E1-breaksnothing

#630 Remove unusued svg file
  web3_foundation_grants_badge_black.svg
Labels: E0-silent

#632 bump substrate
  Cargo.lock
  Cargo.toml
  examples/Cargo.toml
  node-api/Cargo.toml
  primitives/Cargo.toml
  primitives/src/extrinsics/mod.rs
  testing/Cargo.toml
Labels: E1-breaksnothing
