Repository scs/substrate-api-client, pull requests merged in 2023-06, with the labels that each got.

#580 Remove duplicate substrate types
  Cargo.lock
  Cargo.toml
  node-api/Cargo.toml
  node-api/src/metadata.rs
  node-api/src/storage.rs
  primitives/Cargo.toml
  primitives/src/config/mod.rs
  primitives/src/config/substrate_kitchensink.rs
  primitives/src/lib.rs
  primitives/src/serde_impls.rs
  primitives/src/traits.rs
  primitives/src/types.rs
  src/api/api_client.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/chain.rs
  src/api/rpc_api/events.rs
  src/api/rpc_api/frame_system.rs
  src/api/rpc_api/pallet_transaction_payment.rs
  src/api/rpc_api/state.rs
  src/lib.rs
Labels: E2-breaksapi

#587 support metadata v15
  Cargo.lock
  Cargo.toml
  node-api/Cargo.toml
  node-api/src/events.rs
  node-api/src/from_v14_to_v15.rs
  node-api/src/lib.rs
  node-api/src/metadata.rs
  node-api/src/storage.rs
  node-api/src/test_utils.rs
  src/api/rpc_api/events.rs
Labels: E2-breaksapi, dependencies

#585 Readd `KeystoreExt` to `LocalKeystore`
  .github/workflows/ci.yml
  Cargo.lock
  client-keystore/src/keystore_ext.rs
  client-keystore/src/lib.rs
  testing/Cargo.toml
  testing/examples/keystore_tests.rs
Labels: E1-breaksnothing

#589 Update decoder
  Cargo.lock
  node-api/Cargo.toml
  node-api/src/decoder/bit_sequence.rs
  node-api/src/decoder/decode.rs
  node-api/src/decoder/encode.rs
  node-api/src/decoder/mod.rs
  node-api/src/error.rs
  node-api/src/events.rs
  node-api/src/lib.rs
  node-api/src/scale_value/decode.rs
  node-api/src/scale_value/encode.rs
  node-api/src/scale_value/mod.rs
  node-api/src/scale_value/value.rs
Labels: E1-breaksnothing

#594 Make `get_system_account_next_index` available for `no_std`
  src/api/rpc_api/frame_system.rs
Labels: E1-breaksnothing

#596 Introduce folders in node-api to scale down files
  node-api/src/error/dispatch_error.rs
  node-api/src/error/mod.rs
  node-api/src/events/event_details.rs
  node-api/src/events/mod.rs
  node-api/src/lib.rs
  node-api/src/metadata/error.rs
  node-api/src/metadata/from_v14_to_v15.rs
  node-api/src/metadata/metadata_types.rs
  node-api/src/metadata/mod.rs
  node-api/src/metadata/print_metadata.rs
Labels: F5-refactor, E1-breaksnothing

#597 Update Metadata, Error and Events
  Cargo.lock
  compose-macros/src/lib.rs
  node-api/Cargo.toml
  node-api/src/error/dispatch_error.rs
  node-api/src/error/mod.rs
  node-api/src/events/event_details.rs
  node-api/src/events/mod.rs
  node-api/src/lib.rs
  node-api/src/metadata/error.rs
  node-api/src/metadata/metadata_types.rs
  node-api/src/metadata/mod.rs
  node-api/src/metadata/print_metadata.rs
  node-api/src/metadata/variant_index.rs
  node-api/src/scale_value/decode.rs
  node-api/src/scale_value/mod.rs
  node-api/src/test_utils.rs
  src/api/api_client.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/events.rs
  src/api/rpc_api/state.rs
  testing/examples/author_tests.rs
  testing/examples/events_tests.rs
Labels: E2-breaksapi

#599 Update scale-bits and scale-encode
  Cargo.lock
  node-api/Cargo.toml
  node-api/src/scale_value/encode.rs
Labels: E1-breaksnothing, dependencies

#600 Prepare for tag v0.13.0
  Cargo.lock
  Cargo.toml
  client-keystore/Cargo.toml
  compose-macros/Cargo.toml
  examples/Cargo.toml
  node-api/Cargo.toml
  primitives/Cargo.toml
  testing/Cargo.toml
Labels: E1-breaksnothing
