Repository scs/substrate-api-client, pull requests merged in 2023-05, with the labels that each got.

#558 Document feature flags
  Cargo.toml
Labels: E1-breaksnothing

#551 Provide an async example
  .github/workflows/ci.yml
  Cargo.lock
  examples/Cargo.toml
  examples/examples/get_blocks_async.rs
Labels: Z3-example, E1-breaksnothing

#541 Clean up trait bounds
  Cargo.lock
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/event_callback.rs
  examples/examples/event_error_details.rs
  examples/examples/get_account_identity.rs
  examples/examples/get_blocks_async.rs
  examples/examples/get_storage.rs
  examples/examples/print_metadata.rs
  examples/examples/staking_batch_payout.rs
  examples/examples/sudo.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
  primitives/Cargo.toml
  primitives/src/config/mod.rs
  primitives/src/config/polkadot.rs
  primitives/src/config/substrate_kitchensink.rs
  primitives/src/extrinsics/extrinsic_params.rs
  primitives/src/extrinsics/mod.rs
  primitives/src/extrinsics/signer.rs
  primitives/src/lib.rs
  primitives/src/pallet_traits/frame_system_config.rs
  primitives/src/pallet_traits/mod.rs
  primitives/src/pallet_traits/pallet_assets_config.rs
  primitives/src/pallet_traits/pallet_balances_config.rs
  primitives/src/pallet_traits/pallet_contracts_config.rs
  primitives/src/pallet_traits/pallet_staking_config.rs
  primitives/src/serde_impls.rs
  primitives/src/traits.rs
  primitives/src/types.rs
  src/api/api_client.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/chain.rs
  src/api/rpc_api/events.rs
  src/api/rpc_api/frame_system.rs
  src/api/rpc_api/pallet_balances.rs
  src/api/rpc_api/pallet_transaction_payment.rs
  src/api/rpc_api/state.rs
  src/extrinsic/balances.rs
  src/extrinsic/contracts.rs
  src/extrinsic/offline_extrinsic.rs
  src/extrinsic/staking.rs
  src/extrinsic/utility.rs
  testing/examples/author_tests.rs
  testing/examples/chain_tests.rs
  testing/examples/events_tests.rs
  testing/examples/frame_system_tests.rs
  testing/examples/pallet_balances_tests.rs
  testing/examples/pallet_transaction_payment_tests.rs
  testing/examples/state_tests.rs
Labels: E2-breaksapi

#563 Improve Dispatch Errors
  .github/workflows/ci.yml
  examples/examples/event_error_details.rs
  node-api/src/error.rs
  testing/examples/dispatch_errors_tests.rs
Labels: F7-enhancement, E2-breaksapi

#559 Remove extra `is` from example println
  examples/examples/event_error_details.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
Labels: Z3-example, E1-breaksnothing

#567 Update toml versions for tag v0.12.0
  Cargo.lock
  Cargo.toml
  client-keystore/Cargo.toml
  compose-macros/Cargo.toml
  examples/Cargo.toml
  node-api/Cargo.toml
  primitives/Cargo.toml
  test-no-std/Cargo.toml
  testing/Cargo.toml
Labels: E0-silent

#573 Add function `get_system_account_next_index`
  src/api/rpc_api/frame_system.rs
  testing/examples/frame_system_tests.rs
Labels: F7-enhancement, E1-breaksnothing

#575 Move `get_system_account_next_index` to `GetAccountInformation`
  src/api/rpc_api/frame_system.rs
Labels: F7-enhancement, E2-breaksapi

#568 add storage_double_map_key_prefix
  examples/examples/get_storage.rs
  node-api/src/metadata.rs
  node-api/src/storage.rs
  src/api/rpc_api/state.rs
  src/rpc/jsonrpsee_client/mod.rs
Labels: F7-enhancement, E1-breaksnothing

#578 Update dependencies and rust toolchain
  Cargo.lock
  client-keystore/src/lib.rs
  examples/examples/get_blocks_async.rs
  examples/examples/get_storage.rs
  rust-toolchain.toml
Labels: E2-breaksapi, dependencies
