Repository scs/substrate-api-client, pull requests merged in 2023-09, with the labels that each got.

#622 update substrate cmd args in README
  README.md
Labels: E1-breaksnothing, F4-documentation, E0-silent

#650 Switch to using the new polkadot-sdk
  Cargo.lock
  Cargo.toml
  client-keystore/Cargo.toml
  examples/Cargo.toml
  node-api/Cargo.toml
  primitives/Cargo.toml
  test-no-std/Cargo.toml
  testing/Cargo.toml
Labels: E1-breaksnothing, dependencies

#648 Add trait bounds to config: `Index: Default`, `BlockNumber: AtLeast32BitsUnsigned`
  primitives/src/config/mod.rs
Labels: E1-breaksnothing
