Repository scs/substrate-api-client, pull requests merged in 2023-11, with the labels that each got.

#660 Update all dependencies with `cargo update`
  Cargo.lock
  examples/examples/get_account_identity.rs
Labels: F1-security, E1-breaksnothing, dependencies

#667 Add `release-polkadot-vx.x.x` to automatic CI run trigger
  .github/workflows/ci.yml
Labels: F3-test, E0-silent

#670 Update README.md
  README.md
Labels: E1-breaksnothing, F4-documentation, E0-silent

#672 Fix feature order in node-api toml
  node-api/Cargo.toml
Labels: E1-breaksnothing

#673 Update examples in README
  README.md
Labels: F4-documentation, E0-silent

#674 Lower log-level of messages of tungstenite and ws-rpc clients
  src/rpc/tungstenite_client/client.rs
  src/rpc/ws_client/mod.rs
Labels: F7-enhancement, E1-breaksnothing

#675 Enforce F-label on PRs by CI
  .github/release-drafter.yml
  .github/workflows/check-lables.yml
Labels: F3-test, E0-silent

#679 Rpc-api author: Clarify comments about blocking functions
  src/api/rpc_api/author.rs
Labels: E1-breaksnothing, F4-documentation

#678 Remove deprecated functions
  node-api/src/metadata/metadata_types.rs
  primitives/src/config/asset_runtime_config.rs
  primitives/src/config/default_runtime_config.rs
  src/api/rpc_api/author.rs
Labels: E2-breaksapi, F0-miscellaneous
