Repository scs/substrate-api-client, pull requests merged in 2023-12, with the labels that each got.

#556 Create no_std example for extrinsic creation
  .github/workflows/ci.yml
  README.md
  examples/examples/compose_extrinsic.rs
  examples/examples/compose_extrinsic_offline.rs
  primitives/src/extrinsics/extrinsic_params.rs
Labels: Z3-example, E1-breaksnothing, F0-miscellaneous

#680 Update README.md
  README.md
Labels: F4-documentation, E0-silent

#682 Add README FAQ
  README.md
Labels: F4-documentation, E0-silent

#689 Update tungstenite and array-bytes
  Cargo.lock
  Cargo.toml
  client-keystore/Cargo.toml
  client-keystore/src/lib.rs
Labels: E1-breaksnothing, F9-dependencies

#695 Update to polkadot release v1.4.0 commit
  Cargo.lock
  about.toml
  examples/examples/get_account_identity.rs
Labels: E1-breaksnothing, F9-dependencies

#700 node-api: Box Error::DecodeValue and Error::EncodeValue
  .github/workflows/ci.yml
  node-api/src/error/mod.rs
Labels: F6-optimization, E2-breaksapi

#698 Update WithExtrinsicParams to use ExtrinsicSigner<Self>
  examples/examples/benchmark_bulk_xt.rs
  examples/examples/check_extrinsic_events.rs
  examples/examples/contract_instantiate_with_code.rs
  examples/examples/custom_nonce.rs
  examples/examples/get_account_identity.rs
  examples/examples/get_storage.rs
  examples/examples/runtime_update_async.rs
  examples/examples/runtime_update_sync.rs
  examples/examples/staking_batch_payout.rs
  examples/examples/sudo.rs
  examples/examples/transfer_with_tungstenite_client.rs
  examples/examples/transfer_with_ws_client.rs
  primitives/src/config/mod.rs
  testing/examples/author_tests.rs
  testing/examples/chain_tests.rs
  testing/examples/dispatch_errors_tests.rs
  testing/examples/events_tests.rs
  testing/examples/frame_system_tests.rs
  testing/examples/tungstenite_client_test.rs
  testing/examples/ws_client_test.rs
Labels: F2-bug, E1-breaksnothing
