Repository scs/substrate-api-client, pull requests merged in 2023-04, with the labels that each got.

#509 Add Debug to EventRecord
  node-api/src/lib.rs
Labels: F7-enhancement, E1-breaksnothing

#510 Fix Signer encoding
  primitives/src/extrinsics/signer.rs
Labels: F2-bug, E1-breaksnothing

#511 Add static signer
  Cargo.lock
  primitives/Cargo.toml
  primitives/src/extrinsics/signer.rs
Labels: F7-enhancement, E1-breaksnothing

#514 Update rust toolchain
  primitives/src/types.rs
  rust-toolchain.toml
  src/rpc/ws_client/mod.rs
Labels: E1-breaksnothing

#517 Explicitly state edition in rustfmt.toml
  rustfmt.toml
Labels: E0-silent

#515 Udpate toml versions for tag v0.11.0
  Cargo.lock
  Cargo.toml
  client-keystore/Cargo.toml
  compose-macros/Cargo.toml
  examples/Cargo.toml
  node-api/Cargo.toml
  primitives/Cargo.toml
  testing/Cargo.toml
Labels: E0-silent

#522 Make `pallet-staking` and `pallet-contracts` dependencies optional
  Cargo.toml
  examples/Cargo.toml
  primitives/Cargo.toml
  primitives/src/pallet_traits/pallet_contracts_config.rs
  primitives/src/pallet_traits/pallet_staking_config.rs
  src/extrinsic/mod.rs
  testing/Cargo.toml
Labels: F7-enhancement, E2-breaksapi

#529 Add semantic versioning explanation to developer doc
  docs/README.md
Labels: F4-documentation, E0-silent

#530 Add example upgrade section to readme
  README.md
Labels: F4-documentation, E0-silent

#532 Clarify distinction of `Metadata` struct and internal `metadata` field
  examples/examples/print_metadata.rs
  node-api/src/metadata.rs
Labels: E2-breaksapi

#535 Clean up dependencies and fix primitives no_std build
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  README.md
  compose-macros/Cargo.toml
  compose-macros/README.md
  compose-macros/src/lib.rs
  examples/examples/event_error_details.rs
  node-api/Cargo.toml
  node-api/README.md
  primitives/Cargo.toml
  primitives/README.md
  test-no-std/Cargo.toml
  test-no-std/src/main.rs
Labels: F2-bug, F3-test, E2-breaksapi

#538 Expand chain api
  examples/examples/compose_extrinsic_offline.rs
  examples/examples/custom_nonce.rs
  examples/examples/get_blocks.rs
  src/api/mod.rs
  src/api/rpc_api/author.rs
  src/api/rpc_api/chain.rs
  src/api/rpc_api/events.rs
  testing/examples/chain_tests.rs
  testing/examples/events_tests.rs
  testing/examples/pallet_transaction_payment_tests.rs
  testing/examples/state_tests.rs
Labels: E2-breaksapi

#552 Add documentation for the websocket features
  Cargo.toml
  README.md
  compose-macros/src/rpc.rs
Labels: E1-breaksnothing

#545 Add `next_events_from_metadata` and rename `next_event`
  examples/examples/event_callback.rs
  node-api/src/events.rs
  src/api/rpc_api/events.rs
  testing/examples/events_tests.rs
Labels: F7-enhancement, E2-breaksapi

#557 Bump cargo-install to remove Node.js warnings
  .github/workflows/ci.yml
Labels: F3-test, E0-silent
