Repository scs/substrate-api-client, pull requests merged in 2024-03, with the labels that each got.

#746 make stable work for std build
  node-api/src/lib.rs
  src/api/error.rs
  src/lib.rs
  src/rpc/error.rs
Labels: F2-bug, E1-breaksnothing

#750 Add the crates.io version numbers for local dependencies
  Cargo.toml
  compose-macros/Cargo.toml
  examples/async/Cargo.toml
  examples/sync/Cargo.toml
  node-api/Cargo.toml
  test-no-std/Cargo.toml
  testing/async/Cargo.toml
  testing/sync/Cargo.toml
Labels: E1-breaksnothing, F9-dependencies

#751 Rename node-template-runtime dependency
  Cargo.lock
  primitives/Cargo.toml
  primitives/src/extrinsics/mod.rs
  primitives/src/extrinsics/signer.rs
Labels: E1-breaksnothing, F9-dependencies

#754 Rename crate to ac-keystore
  Cargo.lock
  Cargo.toml
  keystore/Cargo.toml
  keystore/src/keystore_ext.rs
  keystore/src/lib.rs
  testing/sync/Cargo.toml
  testing/sync/examples/keystore_tests.rs
Labels: F5-refactor, E2-breaksapi

#756 Update mio dependency that has a vulnerability
  Cargo.lock
Labels: F1-security, E1-breaksnothing

#757 Update and improve crate-metadata
  Cargo.toml
  compose-macros/README.md
  keystore/Cargo.toml
  keystore/README.md
Labels: E1-breaksnothing, F4-documentation
